- name: Deploy my_app service
  hosts: app
  become: true

  vars:
    app_user: my_app
    app_dir: /home/my_app
    service_name: my_app

  tasks:
    - name: Ensure Git is installed
      apt:
        name:
          - git
          - python3-pip
          - python3-setuptools
        state: present
      when: ansible_os_family == "Debian"

    - name: Create application user
      user:
        name: "{{ app_user }}"
        home: "{{ app_dir }}"
        shell: /bin/bash
        create_home: yes

    - name: Mark app directory as safe for Git
      command: git config --global --add safe.directory {{ app_dir }}/app

    - name: Clone code from repo
      git:
        repo: 'https://github.com/ronthesoul/my_app'
        dest: "{{ app_dir }}/app"
        version: main
        force: yes

    - name: Set ownership of app files
      file:
        path: "{{ app_dir }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        recurse: yes

    - name: Ensure that pipenv is installed
      pip:
        name: pipenv
        executable: pip3
        extra_args: --break-system-packages

    - name: Install Python dependencies from Pipfile (safe workaround)
      shell: pipenv install
      args:
        chdir: "{{ app_dir }}/app"

    - name: Run app.py in background using setsid
      shell: |
        setsid pipenv run python3 src/my_app/app.py > /home/my_app/app.log 2>&1 < /dev/null &
      args:
        chdir: "{{ app_dir }}/app"
