version: "3.0"
services:
  ansible-host:
    hostname: ansible-host
    build:
      context: .
      dockerfile: Dockerfile.ansible
    command: ['sleep', 'infinity']
    networks:
      - netgrov
  node1:
    hostname: node1
    build:
      context: .
      dockerfile: Dockerfile.deb
    environment:
      SSH_USERNAME: docker
      SSH_USERPASS: docker
    command: ["/usr/sbin/sshd", "-D"]
    ports:
      - "8000:8000"
    networks:
      - netgrov

networks:
  netgrov:
    name: netgrov
